branch-defaults:
  master:
    environment: prime-production
    group_suffix: null
global:
  application_name: prime
  branch: null
  default_ec2_keyname: catrius-key-pair
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
