version: 2.1

executors:
  default:
    docker:
      - image: circleci/python:latest
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: password

orbs:
  aws-cli: circleci/aws-cli@1.3.0

jobs:
  test:
    executor: default
    steps:
      - checkout
      - run:
          command: poetry config virtualenvs.create false
          name: Disable Poetry virtualenvs creating
      - run:
          command: poetry install
          name: Install dependencies
      - run:
          command: flake8
          name: flake8
      - run:
          command: coverage run manage.py test && coverage
          name: Test
      - run:
          command: bash <(curl -s https://codecov.io/bash)
          name: Upload coverage report to Codecov

  deploy:
    executor: default
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: sudo pip install awsebcli
      - run:
          command: |
            poetry export -f requirements.txt --without-hashes > requirements.txt
            git add .
          name: Freeze requirements.txt
      - run:
          command: eb deploy --staged
          name: Deploy to Elastic Beanstalk

workflows:
  test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
